### ISSUE TITLE
[Anon] Bug report: Ogres.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/kingsofwar#18]
**File:** Ogres.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Kings of War 2E v1 - Ogre Warlord Points is 185, should be 175

**Comment by Ekaznae** [comment]
Hello! Is this from one of the Kickstarter PDFs? Looking at the spreadsheet it's still 185, and he's not listed on the recent sample army list, so I assume so.

**Comment by janstals** [comment]
Hi.  Sorry for taking so long to get back to you.  It is in the latest pdfs
