### ISSUE TITLE
[Anon] Bug report: Kingdoms of Men.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/kingsofwar#24]
**File:** Kingdoms of Men.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Foot guard horde has Melee 4, Defense 4 in statline. Should be Melee 3, Defense 5.

**Comment by Ekaznae** [comment]
Just finished updating EVERYTHING (finally)! I am going to begin applying the changes here and when complete later today will open a Merge/Pull Request for it all.
