### ISSUE TITLE
[Anon] Bug report: Orcs.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/kingsofwar#25]
**File:** Orcs.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** 1.Krudger and Krudger on slasher is one entry, and should be 2 different units, becouse Krudger has goblin sneak options and krudger on slasher shouldn't have it.
2. Krudger should not have any "slasher" option as a mount.
3. Need to add "Krudger on slasher" as new unit with winged slasher option and no goblin sneak options.

**Comment by Ekaznae** [comment]
Just finished updating EVERYTHING (finally)! I am going to begin applying the changes here and when complete later today will open a Merge/Pull Request for it all.
