### ISSUE TITLE
[Anon] Bug report: Empire of Dust.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/kingsofwar#29]
**File:** Empire of Dust.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** While making a roster I noticed I was able to purchase 2 Troops, 1 War Machine, 1 Monster, and 1 Hero while only buying 1 Regiment without any error.  Usually these selections require a Horde/Legion to have them all available.

**Comment by Ekaznae** [comment]
This is a problem within BattleScribe that can't be handled without more options programmed. The best workaround I've managed is including the "(you MUST manually validate quantity)" phrase after Monsters, War Engines and Heroes.
