### ISSUE TITLE
[Anon] Bug report: Salamander Armies.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/kingsofwar#33]
**File:** Salamander Armies.catz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** Yes

**Description:** Both Ghekkotah Skyraiders (3) and Ghekkotah Skyraiders (6) are 200pts.  Ghekkotah Skyraiders (3) should be 130pts.

**Comment by Ekaznae** [comment]
Fixed, will be uploaded soon.
