### ISSUE TITLE
[Anon] Bug report: Kingdoms of Men.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/kingsofwar#39]
**File:** Kingdoms of Men.catz

**BattleScribe version:** 2.00.32

**Platform:** Android

**Dropbox:** Yes

**Description:** Since one of the latter updates the actual (n) values of different skills or spells, e.g. Crushing Strength, is not given anymore. It just shows e.g. "Heal (n)" instead of "Heal (2)".

**Comment by Ekaznae** [comment]
This will be fixed in the large update in just a few days' time. For more details visit https://www.reddit.com/r/BattleScribe/comments/81hxu5/kings_of_war_restructure_feedback_needed/
