### ISSUE TITLE
[Anon] Bug report: The Herd.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/kingsofwar#41]
**File:** The Herd.catz

**BattleScribe version:** 2.01.08

**Platform:** Android

**Dropbox:** No

**Description:** Guardian Brutes should not have pathfinder. But in battlescribe It does

**Comment by Ekaznae** [comment]
This will be fixed in the large update in just a few days' time. For more details visit https://www.reddit.com/r/BattleScribe/comments/81hxu5/kings_of_war_restructure_feedback_needed/
