### ISSUE TITLE
[Anon] Bug report: Night-stalker Armies.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/kingsofwar#43]
**File:** Night-stalker Armies.catz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** Yes

**Description:** Hi,
According to the errata 10/2017 (please find it attached) following nerve values have been changed:
Blood Worms Horde 18/21
Blood Worms Legion 24/27
Needle Fangs Regiment 10/13

Would be great if you found the time updating it.
Thanks for your work. Great job!
Regards, Urs Noetzelmann

**Comment by Ekaznae** [comment]
This will be fixed in the large update in just a few days' time. For more details visit https://www.reddit.com/r/BattleScribe/comments/81hxu5/kings_of_war_restructure_feedback_needed/
