### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Modowaki** [BSData/kingsofwar#44]
Want to update with newest changes

**Comment by BAE2** [comment]
How much experience do you have with editing BS files?  You don't seem to have previous contributions for  anything.  I'll give Ekaznae a nudge to see whether (s)he is planning to do the CoK 2018 updates.

**Comment by Ekaznae** [comment]
Thank you for bringing this to my attention. I haven't done any updates in some time, but will take a look at the errata and Clash of Kings changes and begin working on them. I know there are a couple lingering issues I can take care of at the same time.

**Comment by Ekaznae** [comment]
In the process of doing this, for more details visit https://www.reddit.com/r/BattleScribe/comments/81hxu5/kings_of_war_restructure_feedback_needed/

**Comment by Ekaznae** [comment]
Updates finished!
