### ISSUE TITLE
[Anon] Bug report: Elves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/kingsofwar#47]
**File:** Elves.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Kindred Archer Horde and Regiment have mixed up costs and names. Either the regiment/horde and points values need to be swapped; or stats need to be swapped.

**Comment by Ekaznae** [comment]
Thanks for bringing this up! Fixed, released.
