### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by MPearcy11** [BSData/kingsofwar#54]
Hello, sorry I didn't leave a description when I opened this. I would like to join so I can assist in updating the repo data for the 3rd edition of Kings of War.

**Comment by MPearcy11** [comment]
Hello, sorry I didn't leave a description when I opened this.  I would like to join so I can assist in updating the repo data for the 3rd edition of Kings of War.

**Comment by Ekaznae** [comment]
Sounds great! Now I just need to figure out how to add someone..

**Comment by Ekaznae** [comment]
Nope, not that button!

**Comment by Ekaznae** [comment]
Oh so it's part of the BSData organization. I don't have control of that but I can still merge and update. You could tinker with a forked version of this repository in the meantime! This is exciting! For more reasons than one I JUST got the news that this edition is out.

**Comment by MPearcy11** [comment]
Alright I will work on a forked version for now. Thanks!

**Comment by amis92** [comment]
@Ekaznae I've made you an admin of this repo, you can invite people as Collaborators at https://github.com/BSData/kingsofwar/settings/collaboration

**Comment by Ekaznae** [comment]
@MPearcy11 I have the rules, and have begun creating an updated version of Kings of War.gst, though it looks like the best course of action is going to be a new repo for 3rd Edition. Believe I can have that up, ready for catalogue creation in a day or two. I'm sorry I didn't get back to you until now! I hope that you haven't been working too hard on this... sometimes I'm a bit inconsiderate.

**Comment by MPearcy11** [comment]
Alright that sounds good!  I will hold off on working on the fork of the current one then
