### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by aldarion-jdr** [BSData/kingsofwar#59]
Hello guys !
I'd like to join in order to translate KoW3e to french for Battelscribe.
I forked your repo in Github and even modified KoW3e.gst o a KoW3e-FR.

But Then I cannot get any of armies working with my gst.

Anyways, I'd like to join to do things the right way and distribute the translation.

Tahnk you !

**Comment by amis92** [comment]
Hello, @aldarion-jdr!

First of all, please join us on the BSData Developers discord server: https://discord.gg/UrrPB3T - we'll be much quicker to answer there :)

As for translations, generally we don't support that. Please see https://github.com/BSData/catalogue-development/issues/15
